// <auto-generated />
using System;
using Elena.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Elena.Infrastructure.Migrations
{
    [DbContext(typeof(ElenaContext))]
    partial class ElenaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Elena.Domain.Entities.Lutador", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<double>("AlturaCm")
                        .HasColumnType("double");

                    b.Property<bool>("AtivoNoJogoAtual")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Controle")
                        .HasColumnType("int");

                    b.Property<string>("DificuldadeDeUso")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("EstiloDeLuta")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Forca")
                        .HasColumnType("int");

                    b.Property<string>("Historia")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ImagemUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("JogoDeOrigem")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nacionalidade")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("PesoKg")
                        .HasColumnType("double");

                    b.Property<int>("Tecnica")
                        .HasColumnType("int");

                    b.Property<string>("TierAtual")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Velocidade")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Lutadores");
                });
#pragma warning restore 612, 618
        }
    }
}
